### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by b-long** [meteor-velocity/velocity-website#34]
Hi everybody!  I'm just getting into MeteorJS and I'm really enjoying it 👍 One thing I've found, however, is that the site http://velocity.meteor.com/ appears to be down for a few days now.  In any case, I'm wondering if this is a known issue.

Thanks for all the efforts building Meteor and all the surrounding resources!

cc/ @meteor

p.s. Here's my proof : 

![image](https://cloud.githubusercontent.com/assets/66993/17274303/24f7867a-56a9-11e6-8c6d-0bd459028fc8.png)

**Comment by ghost** [comment]
Velocity has been replaced with https://guide.meteor.com/testing.html.
